# Generated by Django 4.0.2 on 2022-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('is_student', models.BooleanField(null=True)),
                ('is_staff', models.BooleanField(null=True)),
                ('is_prof', models.BooleanField(null=True)),
            ],
        ),
    ]
