# Generated by Django 4.0.3 on 2022-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_student', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_prof', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='database',
        ),
    ]
