# Generated by Django 4.0.3 on 2022-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_profile_delete_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
