# Generated by Django 4.0.2 on 2022-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_profile_delete_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='hall_no',
            field=models.IntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=23, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
