# Generated by Django 4.0.3 on 2022-03-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_profile_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logged_in',
        ),
    ]
