# Generated by Django 4.0.3 on 2022-03-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_full_name_profile_first_name_profile_hall_no_and_more'),
        ('Login', '0005_remove_profile_logged_in'),
    ]

    operations = [
    ]
