# Generated by Django 4.0.3 on 2022-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_remove_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hall_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
