# Generated by Django 4.0.2 on 2022-03-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0002_messorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messOrders',
            new_name='messOrder',
        ),
    ]
