# Generated by Django 4.0.3 on 2022-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0006_remove_messorder_orderedname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messorder',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
