# Generated by Django 4.0.3 on 2022-03-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0008_remove_messorder_ordereddate_remove_messorder_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='item_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='price_6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='quantity_6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='rollno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='messorder',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
