# Generated by Django 4.0.3 on 2022-03-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mess', '0012_messmenu_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='messMenu_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_1', models.CharField(max_length=35, null=True)),
                ('price_1', models.IntegerField(null=True)),
                ('main_2', models.CharField(max_length=35, null=True)),
                ('price_2', models.IntegerField(null=True)),
                ('main_3', models.CharField(max_length=35, null=True)),
                ('price_3', models.IntegerField(null=True)),
                ('main_4', models.CharField(max_length=35, null=True)),
                ('price_4', models.IntegerField(null=True)),
                ('main_5', models.CharField(max_length=35, null=True)),
                ('price_5', models.IntegerField(null=True)),
                ('main_6', models.CharField(max_length=35, null=True)),
                ('price_6', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
