# Generated by Django 4.0.3 on 2022-03-25 22:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mess', '0013_messmenu_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messMenu',
            new_name='messExtras',
        ),
        migrations.RenameModel(
            old_name='messMenu_main',
            new_name='messMain',
        ),
    ]
