# Generated by Django 4.0.3 on 2022-03-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0015_messextras_hall_number_messmain_hall_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messextras',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='user',
        ),
    ]
