# Generated by Django 4.0.3 on 2022-03-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0016_remove_messextras_user_remove_messmain_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messextras',
            name='extras_2',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='extras_3',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='extras_4',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='extras_5',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='extras_6',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='price_5',
        ),
        migrations.RemoveField(
            model_name='messextras',
            name='price_6',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='main_2',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='main_3',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='main_4',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='main_5',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='main_6',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='price_5',
        ),
        migrations.RemoveField(
            model_name='messmain',
            name='price_6',
        ),
    ]
