# Generated by Django 4.0.3 on 2022-03-17 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('room_no', models.CharField(max_length=4, null=True)),
                ('hall_no', models.IntegerField(null=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_prof', models.BooleanField(default=False)),
            ],
        ),
    ]
