# Generated by Django 4.0.3 on 2022-03-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expense_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='expense_last_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='expense_total',
            field=models.IntegerField(default=0),
        ),
    ]
