# Generated by Django 4.0.3 on 2022-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_profile_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
