# Generated by Django 4.0.3 on 2022-03-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_rename_is_prof_profile_is_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_9',
            field=models.IntegerField(default=0),
        ),
    ]
