# Generated by Django 4.0.3 on 2022-03-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_profile_e_0_profile_e_1_profile_e_2_profile_e_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateField(default=0),
        ),
    ]
