# Generated by Django 4.0.3 on 2022-03-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_profile_last_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateField(null=True),
        ),
    ]
