# Generated by Django 4.0.3 on 2022-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpresence',
            name='user_visiting',
            field=models.IntegerField(),
        ),
    ]
