# Generated by Django 4.0.3 on 2022-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0004_hallpresence_timeentered_hallpresence_timeexit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='in_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='laptop',
            field=models.BooleanField(default=False),
        ),
    ]
