# Generated by Django 4.0.3 on 2022-03-18 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hall', '0006_alter_hallpresence_user_visiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
