# Generated by Django 4.0.3 on 2022-03-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0008_hallstudents_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallstudents',
            name='roll_no',
        ),
    ]
