# Generated by Django 4.0.3 on 2022-03-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0009_remove_hallstudents_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='item_6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='price_6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_4',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_5',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='quantity_6',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
