# Generated by Django 4.0.3 on 2022-03-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0010_hallpresence_date_hallpresence_item_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpresence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_1',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_2',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_3',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_4',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_5',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='item_6',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_3',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_4',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_5',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='price_6',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_1',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_2',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_3',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_4',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_5',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='quantity_6',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='hallpresence',
            name='time',
        ),
    ]
