# Generated by Django 4.0.2 on 2022-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0002_alter_messmenu_itemname_alter_messmenu_itemprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
