# Generated by Django 4.0.2 on 2022-03-16 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0003_rename_messorders_messorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='messorder',
            name='orderedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
