# Generated by Django 4.0.3 on 2022-03-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0005_messorder_item_1_messorder_item_2_messorder_item_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messorder',
            name='orderedName',
        ),
        migrations.RemoveField(
            model_name='messorder',
            name='orderedPrice',
        ),
    ]
