# Generated by Django 4.0.3 on 2022-03-19 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0007_messorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messorder',
            name='orderedDate',
        ),
        migrations.RemoveField(
            model_name='messorder',
            name='time',
        ),
    ]
