# Generated by Django 4.0.3 on 2022-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0009_remove_messorder_user_alter_messorder_item_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messorder',
            name='orderedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
