# Generated by Django 4.0.3 on 2022-03-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mess', '0011_remove_messmenu_itemname_remove_messmenu_itemprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenu',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
