# Generated by Django 4.0.3 on 2022-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0003_remove_hallpresence_timeentered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='timeEntered',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hallpresence',
            name='timeExit',
            field=models.DateTimeField(null=True),
        ),
    ]
