# Generated by Django 4.0.3 on 2022-03-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0011_remove_hallpresence_date_remove_hallpresence_item_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='hall_numnber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HallStudents',
        ),
    ]
