# Generated by Django 4.0.3 on 2022-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0012_hallpresence_hall_numnber_delete_hallstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='room_visiting',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
