# Generated by Django 4.0.3 on 2022-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0013_hallpresence_room_visiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallpresence',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
    ]
