# Generated by Django 4.0.3 on 2022-03-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hall', '0015_hallpresence_first_name_hallpresence_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallpresence',
            name='in_transit',
        ),
    ]
